title: TravelBuddy
description: "Connect with fellow travelers on the same journey"
logo: /assets/images/logo.png
email: support@travelbuddy-app.com
show_downloads: false
google_analytics:
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

# Multilingual settings
languages: ["en", "fr"]
default_lang: "en"
exclude_from_localization: ["assets", "images", "css", "js"]
parallel_localization: true

# Navigation
nav:
  en:
    home: "Home"
    community: "Community"
    privacy: "Privacy"
    legal: "Legal Notices"
    help: "Help & Support"
    contact: "Contact Us"
  fr:
    home: "Accueil"
    community: "Communauté"
    privacy: "Confidentialité"
    legal: "Mentions Légales"
    help: "Aide & Support"
    contact: "Contactez-nous"